<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Register_form_model extends CI_Model
{

    public $table = 'register_form';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('nomor_wa', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('usia', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('info_pelatihan', $q);
	$this->db->or_like('daerah_domisili', $q);
	$this->db->or_like('tujuan_pelatihan', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('platform_jobseeker', $q);
	$this->db->or_like('jenis_pekerjaan', $q);
	$this->db->or_like('jenis_usaha_bisnis', $q);
	$this->db->or_like('sekolah_universitas', $q);
	$this->db->or_like('kategori_pelatihan', $q);
	$this->db->or_like('link_sosmed', $q);
	$this->db->or_like('created_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('nomor_wa', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('usia', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('info_pelatihan', $q);
	$this->db->or_like('daerah_domisili', $q);
	$this->db->or_like('tujuan_pelatihan', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('platform_jobseeker', $q);
	$this->db->or_like('jenis_pekerjaan', $q);
	$this->db->or_like('jenis_usaha_bisnis', $q);
	$this->db->or_like('sekolah_universitas', $q);
	$this->db->or_like('kategori_pelatihan', $q);
	$this->db->or_like('link_sosmed', $q);
	$this->db->or_like('created_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Register_form_model.php */
/* Location: ./application/models/Register_form_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-09-28 10:08:59 */
/* http://harviacode.com */